include(CheckCXXCompilerFlag)

check_cxx_compiler_flag(-pedantic PEDANTIC_SUPPORTED)
check_cxx_compiler_flag(-Wcast-qual CAST_QUAL_SUPPORTED)
check_cxx_compiler_flag(-Winit-self INIT_SELF_SUPPORTED)
check_cxx_compiler_flag(-Woverloaded-virtual OVERLOADED_VIRTUAL_SUPPORTED)
check_cxx_compiler_flag(-Wredundant-decls REDUNDANT_DECLS_SUPPORTED)
check_cxx_compiler_flag(-Wredundant-decls REDUNDANT_DECLS_SUPPORTED)

if (NOT MSVC)
	add_compile_options(-Wall -Wextra -Werror)
endif()

if (PEDANTIC_SUPPORTED)
    add_compile_options(-pedantic)
endif()

if (CAST_QUAL_SUPPORTED)
    add_compile_options(-Wcast-qual)
endif()
if (INIT_SELF_SUPPORTED)
    add_compile_options(-Winit-self)
endif()
if (OVERLOADED_VIRTUAL_SUPPORTED)
    add_compile_options(-Woverloaded-virtual)
endif()
if (REDUNDANT_DECLS_SUPPORTED)
    add_compile_options(-Wredundant-decls)
endif()
